### ISSUE TITLE
allow for marking acquisitions completed

### ISSUE THREAD

**Issue by EliotGann** [NSLS-II-SST/rsoxs_scans#14]
and outputting these to a new sheet with metadata about acquisition (uid from bluesky, timestamp minimum), remove option to delete acquisition, make this the default option.  also remove plan history potentially?

**Comment by EliotGann** [comment]
as with the current bar object, I think we will need to store 'completed_acquisitions' as a special key in each sample, and loop through them as we do with acquisitions to output to a separate sheet.

**Comment by EliotGann** [comment]
this will certainly need some tweaks to the main rsoxs code as well - in fact most of the changes may be in that repository - but it is easier to track as part of this project

**Comment by BijalBPatel** [comment]
Hey Eliot, adding my notes from our conversation re: this: to your list above:

Goal: Revision to spreadsheet ingest/output scheme for workflow improvements.

Desired Qualities:
- Reformulate spreadsheet as a 'living' document that only gains information as scans progress (no deletion)
- Successive versions of the sheet should either preserve the initial formatting/rules or be easy to copy/paste back into the initial sheet format
- Enhance output metadata with information about scans that have run already

Possible Task List and ideas for Implementation:
- [ ] Revise Sample Spreadsheet Format to include new sheet "CompletedAcquisitions". (Possibly rename "Acquisitions" to "PlannedAcquisitions") Also may be a good time to address #17 
- [ ] Define the list of all the metadata columns that will be input or output. I suggest these just be added into the spreadsheet "SheetRulesAndMetaData" as new rows so that the documentation exists for users to understand what they mean. 
- [ ] A possible implementation:

- in defaults.py, make 3 template dicts of metadata parameters that you will either import or export for each acquisition and provide default values (blank string or whatever). 
- When building the dict for import or export start by initializing it to the defaults value, then loop through the acquisition in memory and update the dictionary entries.
- When exporting, set the [excel writer to append mode](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html) and export in two stages. (1) First use df.to_excel(columns=list([relevantDefaultDictionary])) to output the columns that need to match the input spreadsheet in order. Then  (2) use df.to_excel() again for any extra columns (will require you sub-setting out the already exported columns)

**Comment by EliotGann** [comment]
so we need a blank default xlsx file that we can copy and append to?  this would contain all of the header stuff on bar and acquisitions, the instructions sheet and the lookup sheet, with all of the validation rules already intact?

**Comment by EliotGann** [comment]
I'm not sure I see how that could work to be honest.

**Comment by BijalBPatel** [comment]
So two ways to do it I think:

Easy way is to have the users manually fill in the first sheet as we do now.

Then the beamline code runs and outputs a sheets WITHOUT the fancy excel rules, but with all the columns in the same order.

Then for the next round of runs, the users copy-paste the data cells from the output sheet into the formatted rule spreadsheet and proceed from there. <- this step is important because then when the users add new scans, they do so with the benefit of all the formatting and documentation.



Hard way is to do the appending into a blank xlsx that has headers and data validation programmatically. Yeah seems hard/ like not worth the effort atm.

**Comment by EliotGann** [comment]
OK, I can definitely see how to 1.) put columns in the same order as the example dictionary 2.) add extra columns that are not in the default dictionary, but do have information that will populate if you add them.  Maybe that is enough for now.  the extra columns will get out of order though.

**Comment by BijalBPatel** [comment]
If i understand it correctly, when you do `list(dictionaryName)` it gives you a list of keys in the order they were added to the original dictionary.

So if you are careful about how you add the columns in the first place, then always do `df.to_excel(columns=list(dictionaryName))` it should give you all columns exported in order.

You could probably actually just do the export in one step then. 

So - build exportdf by copying the defaultExportDict, then add key:values for the extra columns to the dataframe, then do to_excel using the columns= function.

**Comment by BijalBPatel** [comment]
As per video call 230123:

Quality of life improvement: 

- [ ] Prepend and Append naming convention to exported sheets : asRun_[YYYYMMDD][hhmm]"UserString".xlsx , where "Userstring" is provided as a parameter

**Comment by EliotGann** [comment]
well, I can't get a default order to work, cause it has to be identical for each, which means every acquisition is wrong.  I tried to get the column order in the pandas dataframe to match the input order, but that doesn't seem to propagate through.  I might try again later

**Comment by EliotGann** [comment]
Ok!  I figured out how to fix the order and make the columns the same as the input.  also, acquisition marking rather than deleting is done.  I think I will close this unless we can think of a way to add in the rest of the instructions and stuff somehow

**Comment by BijalBPatel** [comment]
Agree, I think this is good for the indefinite future, given that this will be replaced eventually with the queue server etc. scheme.

If the excel sheet survives past 2023-3, or if the queue server option is taken off the table,  it would be worth revisiting the rest of instructions etc.

**Comment by pbeaucage** [comment]
![](https://imgs.xkcd.com/comics/code_lifespan.png)
Just leaving that there....
